export const Imagepath = {
    add_to_card: require('../assest/Image/add_to_card_Aactive.png'),
    bacgroundTop:require('../assest/Image/backgroundTop.png'),
    logo:require('../assest/Image/logo.png'),
    menu:require('../assest/Image/menu.png'),
    addtocard:require('../assest/Image/addtocard.png'),
    bottomimg:require('../assest/Image/bottomimg.jpeg'),
    frutes:require('../assest/Image/frutes.png'),
    DRY:require('../assest/Image/DRY.png'),
    frpimg:require('../assest/Image/frappimg.jpeg'),
    frtimg2:require('../assest/Image/frtimg2.jpeg'),
    frtimg3:require('../assest/Image/frtimg3.jpeg'),
    potato:require('../assest/Image/Potatoes.png'),
    onions:require('../assest/Image/onions.png'),
    mirchi:require('../assest/Image/mirchi.png'),
    voctar6:require('../assest/Image/Vector6.png'),
    Home:require('../assest/Image/home.png'),
    Cartegry:require('../assest/Image/hrt.png'),
    foverty:require('../assest/Image/imgbag.png'),
    Cart:require('../assest/Image/box.png'),
    ang:require('../assest/Image/ang.jpeg'),
    Apple:require('../assest/Image/apple.webp'),
    banan:require('../assest/Image/banana.jpeg'),
    Chiku:require('../assest/Image/chik.jpeg'),
    nar:require('../assest/Image/nar.jpeg'),
    Papi:require('../assest/Image/papi.jpeg'),
    dill:require('../assest/Image/ditt.png'),
    share:require('../assest/Image/share.png'),
    threelins:require('../assest/Image/threelins.png'),
    search:require('../assest/Image/search.png'),
    Apples:require('../assest/Image/Apples.png'),
    brocoli:require('../assest/Image/broccoli.png'),
    mangoexotic:require('../assest/Image/mangosteen.png'),
    ifresh:require('../assest/Image/ifresh.jpeg'),
    location:require('../assest/Image/loc.png'),
    map:require('../assest/Image/map2.png'),



    
}